# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  database: c316db # replace this with the db created in step 5a
  username: Creighton # replace this with your own user name
  password: caseyokeefe # replace this with your own password
  host: localhost
  encoding: UTF8
  pool: 5
  timeout: 5000
